### ISSUE TITLE
Wayland support?

### ISSUE THREAD

**Issue by eternal-sorrow** [anarsoul/io.github.softfever.OrcaSlicer#1]
Is it possible to support Wayland with build options? Right now even if I allow access to Wayland with Flatseal, it doesn't start.

Or are the code changes required to support it?

**Comment by anarsoul** [comment]
I hope you do understand that this repo is a downstream package. Wayland isn't supported by upstream Orca Slicer, it would need wxWidgets to be updated and some additional fixes. I have no interest in working on that.

**Comment by eternal-sorrow** [comment]
Of course I understand.

>it would need wxWidgets to be updated and some additional fixes

That's what I was asking about. Thanks.

>I have no interest in working on that.

Of course. That's okay.

Do you know anything about Orca Slicer development cycle? Do they merge changes from Bambu Studio, or is it a completely independent project? Because I see a [feature request](https://github.com/bambulab/BambuStudio/issues/2595) for wayland support in Bambu, but no such request for Orca.

**Comment by anarsoul** [comment]
> Do you know anything about Orca Slicer development cycle?

Sorry, no idea. I don't have a direct contact with Orca Slicer dev(s).

> Because I see a https://github.com/bambulab/BambuStudio/issues/2595 for wayland support in Bambu, but no such request for Orca.

Feel free to open an issue at https://github.com/softFever/OrcaSlicer/issues/

**Comment by eternal-sorrow** [comment]
Alright!
